import pcImg from "../../assets/pc.png";

export const computersData = [
  {
    title: "PC-1",
    img: pcImg,
    cpu: "CPU-1",
    gpu: "GPU-1",
    memoryType: "RAM-TYPE-1",
    ram: "RAM-1",
    ssd: "SSD-1",
    price: "10000",
  },
  {
    title: "PC-2",
    img: "https://it-blok.com.ua/image/cache/catalog/Korpusa/Frontier%20SAMBURU%20Black/1-268x268.png.pagespeed.ce.DFhY70BW2P.png",
    cpu: "CPU-2",
    gpu: "GPU-2",
    memoryType: "RAM-TYPE-2",
    ram: "RAM-2",
    ssd: "SSD-2",
    price: "20000",
  },
  {
    title: "PC-3",
    img: "https://it-blok.com.ua/image/cache/catalog/Korpusa/Frontier%20HIMBA%2022A%20Black/1-268x268.png.pagespeed.ce.9TnL_5qBQW.png",
    cpu: "CPU-3",
    gpu: "GPU-3",
    memoryType: "RAM-TYPE-3",
    ram: "RAM-3",
    ssd: "SSD-3",
    price: "30000",
  },
  {
    title: "PC-4",
    img: "https://it-blok.com.ua/image/cache/catalog/Korpusa/Vinga%20Ghost/1-268x268.png.pagespeed.ce.28BSpKx_4F.png",
    cpu: "CPU-4",
    gpu: "GPU-4",
    memoryType: "RAM-TYPE-4",
    ram: "RAM-4",
    ssd: "SSD-4",
    price: "40000",
  },
  {
    title: "PC-5",
    img: "https://versum.ua/image/cache/catalog/products/pc/2e-gaming-calleo-argb-black-1-358x358.png",
    cpu: "CPU-5",
    gpu: "GPU-5",
    memoryType: "RAM-TYPE-5",
    ram: "RAM-5",
    ssd: "SSD-5",
    price: "50000",
  },
  {
    title: "PC-6",
    img: "https://it-blok.com.ua/image/cache/catalog/Korpusa/Gamemax%20Edge/1-367x367.png.pagespeed.ce.VwUGCOZMiN.png",
    cpu: "CPU-6",
    gpu: "GPU-6",
    memoryType: "RAM-TYPE-6",
    ram: "RAM-6",
    ssd: "SSD-6",
    price: "60000",
  },
  {
    title: "PC-7",
    img: "https://it-blok.com.ua/image/cache/catalog/Korpusa/Gamemax%20Destroyer%20Mesh%20Black/1-268x268.png.pagespeed.ce.u5vUbEPC9n.png",
    cpu: "CPU-7",
    gpu: "GPU-7",
    memoryType: "RAM-TYPE-7",
    ram: "RAM-7",
    ssd: "SSD-7",
    price: "70000",
  },
  {
    title: "PC-8",
    img: "https://it-blok.com.ua/image/cache/catalog/Korpusa/2E%20Gaming%20CALLEO%20ARGB%20White/1-367x367.png.pagespeed.ce.LcnYBBwCVb.png",
    cpu: "CPU-8",
    gpu: "GPU-8",
    memoryType: "RAM-TYPE-8",
    ram: "RAM-8",
    ssd: "SSD-8",
    price: "80000",
  },
  {
    title: "PC-9",
    img: "https://it-blok.com.ua/image/cache/catalog/Korpusa/Vinga%20CS316B/1-367x367.png.pagespeed.ce.ndPU6HlkQ8.png",
    cpu: "CPU-9",
    gpu: "GPU-9",
    memoryType: "RAM-TYPE-9",
    ram: "RAM-9",
    ssd: "SSD-9",
    price: "90000",
  },
  {
    title: "PC-10",
    img: "https://it-blok.com.ua/image/cache/catalog/Korpusa/Deepcool%20MATREXX%2030/1-367x367.png.pagespeed.ce.a2tK4-D_WV.png",
    cpu: "CPU-10",
    gpu: "GPU-10",
    memoryType: "RAM-TYPE-10",
    ram: "RAM-10",
    ssd: "SSD-10",
    price: "100000",
  },
  {
    title: "PC-11",
    img: "https://it-blok.com.ua/image/cache/catalog/Korpusa/Gamemax%20Black%20Hole/1-367x367.png.pagespeed.ce.Z2-y5l14AE.png",
    cpu: "CPU-11",
    gpu: "GPU-11",
    memoryType: "RAM-TYPE-11",
    ram: "RAM-11",
    ssd: "SSD-11",
    price: "110000",
  },
  {
    title: "PC-12",
    img: "https://it-blok.com.ua/image/cache/catalog/Korpusa/Deepcool%20MATREXX%2050%204FS/1-367x367.png.pagespeed.ce._G5ttHQfu-.png",
    cpu: "CPU-12",
    gpu: "GPU-12",
    memoryType: "RAM-TYPE-12",
    ram: "RAM-12",
    ssd: "SSD-12",
    price: "120000",
  },
];
