import pcImg from "../../assets/pc.png";

export const computersData = [
  {
    title: "PC-1",
    img: pcImg,
    cpu: "CPU-1",
    gpu: "GPU-1",
    memoryType: "RAM-TYPE-1",
    ram: "RAM-1",
    ssd: "SSD-1",
    price: "10000",
  },
  {
    title: "PC-2",
    img: pcImg,
    cpu: "CPU-2",
    gpu: "GPU-2",
    memoryType: "RAM-TYPE-2",
    ram: "RAM-2",
    ssd: "SSD-2",
    price: "20000",
  },
  {
    title: "PC-3",
    img: pcImg,
    cpu: "CPU-3",
    gpu: "GPU-3",
    memoryType: "RAM-TYPE-3",
    ram: "RAM-3",
    ssd: "SSD-3",
    price: "30000",
  },
  {
    title: "PC-4",
    img: pcImg,
    cpu: "CPU-4",
    gpu: "GPU-4",
    memoryType: "RAM-TYPE-4",
    ram: "RAM-4",
    ssd: "SSD-4",
    price: "40000",
  },
  {
    title: "PC-5",
    img: pcImg,
    cpu: "CPU-5",
    gpu: "GPU-5",
    memoryType: "RAM-TYPE-5",
    ram: "RAM-5",
    ssd: "SSD-5",
    price: "50000",
  },
  {
    title: "PC-6",
    img: pcImg,
    cpu: "CPU-6",
    gpu: "GPU-6",
    memoryType: "RAM-TYPE-6",
    ram: "RAM-6",
    ssd: "SSD-6",
    price: "60000",
  },
  {
    title: "PC-7",
    img: pcImg,
    cpu: "CPU-7",
    gpu: "GPU-7",
    memoryType: "RAM-TYPE-7",
    ram: "RAM-7",
    ssd: "SSD-7",
    price: "70000",
  },
  {
    title: "PC-8",
    img: pcImg,
    cpu: "CPU-8",
    gpu: "GPU-8",
    memoryType: "RAM-TYPE-8",
    ram: "RAM-8",
    ssd: "SSD-8",
    price: "80000",
  },
];
